apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-catalog
  template:
    metadata:
      labels:
        app: rso1920-catalog
    spec:
      containers:
        - image: rso1920/catalog:latest
          name: rso1920-catalog
          env:
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://10.28.9.211:8088
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://35.241.190.224:5432/catalog
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
          ports:
            - containerPort: 8088
              name: catalog-server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: catalog-server
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: catalog-server
            initialDelaySeconds: 60
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-catalog
spec:
  type: ClusterIP
  ports:
    - port: 8088
      protocol: TCP
      targetPort: catalog-server
  selector:
    app: rso1920-catalog
