kumuluzee:
  name: rso-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8088
    http:
      port: 8088
  datasources:
    - jndi-name: jdbc/CatalogDS
      connection-url: jdbc:postgresql://192.168.1.7:5435/catalog
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

rest-config:
  download-file-api-url: http://localhost:8090/