kumuluzee:
  name: rso1920-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8088
    http:
      port: 8088
  datasources:
    - jndi-name: jdbc/CatalogDS
      connection-url: jdbc:postgresql://localhost:5435/catalog
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CatalogDS
  metrics:
    web-instrumentation:
      - name: catalog-endpoint
        url-pattern: /v1/catalog/*
      - name: file-metadata-endpoint
        url-pattern: /v1/fileMetadata/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="cfffe2f5-63d9-4c32-a175-636585889410-ls.logit.io"
                              port="21975" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'

rest-config:
  download-file-api-url: http://localhost:8090/